### ISSUE TITLE
Testing: add_test() does not register dependencies correctly

### ISSUE THREAD

**Issue by Xunie** [asheplyakov/cln#1]
https://github.com/asheplyakov/cln/blob/ece08e37c01ac7ed1d4d600f881fbf90c9338cd3/tests/CMakeLists.txt#L42-L56
The code above does not add the test to the default 'test' target. I don't really know why this is happening.

Additionally, running `make check` does not actually depend on the building of the tests so it fails to find the tests it depends on.

I don't know how much of a 'feature' this is. I think I'd go nuts if every time I run 'test' my build system it also proceeds to test CLN. A project which I haven't even changed any code on.

Tthen again, failures do crop up every now and then and it's a good sanity check. As such, I think it's a bug because more testing is better.

If this is a bug, fix as follows:
```
add_test(NAME ${thename} COMMAND ${thename})
```

That is: remove the `$<TARGET_FILE:            >` part...

**Comment by Xunie** [comment]
If the code is being changed, it might be nice to remove the `add_dependencies()` calls on 53 and 54 and replace them with a single call that adds it to the `test_cln` target.

If we do the same thing for GiNaC, the result will be a default generated `test` target that tests all dependencies, `test_cln` and `test_ginac` would test respectively...

**Comment by asheplyakov** [comment]
> The code above does not add the test to the default 'test' target. I don't really know why this is happening.

That's a bug. I had to use both CMake and autotools, thus I wanted `make check` to always work.
As a result I haven't bothered to add proper dependencies to the `test` target.

> That is: remove the $<TARGET_FILE: > part...

`$<TARGET_FILE:` is correct and necessary. See,  when (cross-) compiling for Windows
DLLs and executables go into the `${CMAKE_CURRENT_BINARY_DIR}/bin` directory,
so it's possible to run tests without fiddling with `%PATH%`. Hence 

> Additionally, running make check does not actually depend on the building of the tests 

Can't reproduce this one:

```bash
rm -rf _build
mkdir _build
cd _build && cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
cmake --build . -t check -j8
#
# skipped lots of boring output
#
[100%] Linking CXX executable tests
gmake[3]: Leaving directory '/home/asheplyakov/work/sw/cln/_build_native'
[100%] Built target tests
gmake[3]: Entering directory '/home/asheplyakov/work/sw/cln/_build_native'
Scanning dependencies of target check
gmake[3]: Leaving directory '/home/asheplyakov/work/sw/cln/_build_native'
gmake[3]: Entering directory '/home/asheplyakov/work/sw/cln/_build_native'
Test project /home/asheplyakov/work/sw/cln/_build_native
    Start 1: exam
1/2 Test #1: exam .............................   Passed    0.05 sec
    Start 2: tests
2/2 Test #2: tests ............................   Passed    6.96 sec

100% tests passed, 0 tests failed out of 2

Total Test time (real) =   7.02 sec
gmake[3]: Leaving directory '/home/asheplyakov/work/sw/cln/_build_native'
[100%] Built target check
gmake[2]: Leaving directory '/home/asheplyakov/work/sw/cln/_build_native'
gmake[1]: Leaving directory '/home/asheplyakov/work/sw/cln/_build_native'
```

**Comment by asheplyakov** [comment]
> I think I'd go nuts if every time I run 'test' my build system it also proceeds to test CLN.

Running CLN test suite takes about 12 seconds (on my dual-core core i3-7100U). Is it really **that** bad?

> A project which I haven't even changed any code on.

In the past CLN has experienced quite a number of compiler bugs (there've been a joke that CLN is a GCC stress test). These days compilers are much better, but running the test suite is a very good idea anyway.  CLN developers don't test every possible compiler/options/OS.

**Comment by asheplyakov** [comment]
> If the code is being changed, it might be nice to remove the add_dependencies() calls on 53 and 54 and replace them with a single call that adds it to the test_cln target.

Let me explain a bit why the `test_suite` target exists. Usually I compile GiNaC (along with CLN) like this:
```bash
cmake -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_CXX_COMPILER_LAUNCHER=buildcache ..
cmake --build . -t test_suite # builds libraries and tests, but don't execute them
ctest -j4
```
This way both compilation and execution of tests make use of all available cores/threads.
Perhaps CMake could do that automatically, but I guess lots of test suites are not designed for parallel execution.

**Comment by Xunie** [comment]
I think I messed up and there is no dependency bug. Weird. I think the most likely cause was that my build was messed up somehow. I *am* still ironing out some rough edges on my own CMake build. I regenerated my build from scratch and it all seems to work now.

HOWEVER: The CLN test suite of 60 tests takes 3 minutes to run on my Linux machine when running `make -j 32 test`. I'd expect parallelism when that happens. Turns out with `ctest -j 32` things are completely fine and parallelized. I think that once again, the issue lies with me and not your build.

I doff my hat to you. Спасибо!

**Comment by Xunie** [comment]
Okay shit. It's not just a me problem. Sorry, dude.

Steps to reproduce on Linux:
```
git clone --recursive https://github.com/Xunie/ginac-problem.git
mkdir ginac-problem-build
cd ginac-problem-build
cmake ../ginac-problem
make -j
ctest -j
```

Results in a lot of unbuilt tests trying to be run. Is this a bug or a feature?

**Comment by Xunie** [comment]
> As a result I haven't bothered to add proper dependencies to the `test` target.
I understand now.

* `test` runs all tests
* `check` runs all tests but also compiles them before hand (even on Linux!, **No bug here!**)
* `ctest` just runs all test and doesn't compile them (duh)
* there is no dependency bug because once again, *I* am the problem.

I'll leave it up to you to decide whether proper dependencies on the 'test' target are desirable.

Sorry for the confusion, Alexey.
Thanks again!

**Comment by asheplyakov** [comment]
> ctest just runs all test and doesn't compile them (duh)

I think this behavior is unfriendly, `ctest` could have easily run `cmake --build . -t test` instead of complaining. Also cmake could run test concurrently by default (at least with ninja generator, where parallel build is the default). But there's nothing CLN could possibly do about it.

**Comment by Xunie** [comment]
I guess we can close the issue then.
